[toolchain]
anchor_version = "0.29.0"
solana_version = "1.17.15"

[features]
seeds = false
skip-lint = false

[programs.devnet]
simple_program = "ESyxaZxC2oBA4FmsRe94U62hqQW2e8hSPZWMEnrarUM"

[programs.localnet]
simple_program = "ESyxaZxC2oBA4FmsRe94U62hqQW2e8hSPZWMEnrarUM"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "./config/wallet.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/test_localnet.ts"
test-devnet = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/test_devnet.ts"

[test]
startup_wait = 5000
shutdown_wait = 2000
upgradeable = true
